const styles = {
  container: {
    maxWidth: '1440px',
    margin: '40px auto',
    padding: '32px',
    background: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.08)',
    fontFamily: 'Inter, system-ui, sans-serif',
    animation: 'fadeIn 0.5s ease-out',
  },
  title: {
    fontSize: '1.875rem',
    fontWeight: 700,
    color: '#1f2937',
    marginBottom: '24px',
    textAlign: 'center',
    letterSpacing: '-0.025em',
  },
  errorMessage: {
    background: '#fef2f2',
    color: '#dc2626',
    padding: '12px 16px',
    borderRadius: '8px',
    marginBottom: '24px',
    fontSize: '0.875rem',
    textAlign: 'center',
    animation: 'slideIn 0.3s ease-out',
  },
  successMessage: {
    background: '#f0fdf4',
    color: '#16a34a',
    padding: '12px 16px',
    borderRadius: '8px',
    marginBottom: '24px',
    fontSize: '0.875rem',
    textAlign: 'center',
    animation: 'slideIn 0.3s ease-out',
  },
  tableWrapper: {
    overflowX: 'auto',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
  },
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    background: '#ffffff',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  th: {
    padding: '16px',
    textAlign: 'left',
    fontSize: '0.875rem',
    color: '#ffffff',
    background: '#2563eb',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  td: {
    padding: '16px',
    textAlign: 'left',
    fontSize: '0.875rem',
    color: '#1f2937',
    borderBottom: '1px solid #e5e7eb',
  },
  button: {
    padding: '8px 12px',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '0.75rem',
    fontWeight: 500,
    transition: 'background 0.2s, transform 0.2s',
  },
  acceptButton: {
    background: '#16a34a',
    color: '#ffffff',
  },
  rejectButton: {
    background: '#dc2626',
    color: '#ffffff',
  },
  editButton: {
    background: '#d97706',
    color: '#ffffff',
  },
  deleteButton: {
    background: '#dc2626',
    color: '#ffffff',
  },
  uploadButton: {
    background: '#16a34a',
    color: '#ffffff',
  },
  submitButton: {
    background: '#2563eb',
    color: '#ffffff',
    padding: '12px 24px',
    fontSize: '0.875rem',
  },
  cancelButton: {
    background: '#e5e7eb',
    color: '#1f2937',
    padding: '12px 24px',
    fontSize: '0.875rem',
  },
  form: {
    display: 'grid',
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#374151',
  },
  input: {
    padding: '12px 16px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    fontSize: '0.875rem',
    color: '#1f2937',
    background: '#ffffff',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  noData: {
    textAlign: 'center',
    fontSize: '1rem',
    color: '#6b7280',
    padding: '24px 0',
  },
  '@keyframes fadeIn': {
    from: { opacity: 0, transform: 'translateY(10px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
  },
  '@keyframes slideIn': {
    from: { opacity: 0, transform: 'translateX(-10px)' },
    to: { opacity: 1, transform: 'translateX(0)' },
  },
  '@media (max-width: 768px)': {
    container: {
      margin: '24px 16px',
      padding: '24px',
    },
    tableWrapper: {
      margin: '0 -16px',
    },
    title: {
      fontSize: '1.5rem',
    },
  },
};

export default styles;